-- Migration 0012: add local_intro column to articles table.
-- This nullable TEXT field holds a 150-250 word Kentucky-focused context
-- paragraph generated by the AI ingest pipeline.  When populated it signals
-- that the article has original local content and the canonical URL should
-- resolve to localkynews.com rather than the original external source.
ALTER TABLE articles ADD COLUMN local_intro TEXT;
