-- Migration 0010: Add Kentucky county school Facebook page feeds and Perry Advocate Facebook news feed.
-- fetch_mode = 'facebook-page' uses the mbasic.facebook.com scraper.
-- Posts are short by design; the word-count minimum is skipped for these feeds.
-- Each feed is pinned to its county via default_county so items are always
-- tagged to the correct county without relying on article-text detection.

INSERT OR IGNORE INTO feeds (id, name, category, url, state_code, default_county, region_scope, fetch_mode, scraper_id, enabled) VALUES
  ('ky-fb-school-adair', 'Adair County Schools', 'Kentucky - Schools', 'https://www.facebook.com/adaircoschools/', 'KY', 'Adair', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-allen', 'Allen County-Scottsville High School', 'Kentucky - Schools', 'https://www.facebook.com/allencountyscottsvillehighschool/', 'KY', 'Allen', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-anderson', 'Anderson County Schools', 'Kentucky - Schools', 'https://www.facebook.com/acboe/', 'KY', 'Anderson', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-ballard', 'Ballard County Schools', 'Kentucky - Schools', 'https://www.facebook.com/100063755730159/', 'KY', 'Ballard', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-barren', 'Barren County Schools', 'Kentucky - Schools', 'https://www.facebook.com/barrenschools/', 'KY', 'Barren', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-bath', 'Bath County Schools', 'Kentucky - Schools', 'https://www.facebook.com/BathCountySchoolsKY/', 'KY', 'Bath', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-bell', 'Bell County School District', 'Kentucky - Schools', 'https://www.facebook.com/BellCountySchoolDistrict/', 'KY', 'Bell', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-boone', 'Boone County Schools', 'Kentucky - Schools', 'https://www.facebook.com/TheBooneCountySchools/', 'KY', 'Boone', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-bourbon', 'Bourbon County School District', 'Kentucky - Schools', 'https://www.facebook.com/BourbonCountySchools/', 'KY', 'Bourbon', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-boyd', 'Boyd County Public School District', 'Kentucky - Schools', 'https://www.facebook.com/100065164023982/', 'KY', 'Boyd', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-boyle', 'Boyle County Schools', 'Kentucky - Schools', 'https://www.facebook.com/boylecounty/', 'KY', 'Boyle', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-bracken', 'Bracken County Schools', 'Kentucky - Schools', 'https://www.facebook.com/BrackenCountySchools/', 'KY', 'Bracken', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-breathitt', 'Breathitt County Schools', 'Kentucky - Schools', 'https://www.facebook.com/BreathittCountySchools/', 'KY', 'Breathitt', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-breckinridge', 'Breckinridge County School District', 'Kentucky - Schools', 'https://www.facebook.com/breckinridgecountyschools/', 'KY', 'Breckinridge', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-butler', 'Butler County Schools', 'Kentucky - Schools', 'https://www.facebook.com/ButlerCountySchools/', 'KY', 'Butler', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-caldwell', 'Caldwell County Schools', 'Kentucky - Schools', 'https://www.facebook.com/CaldwellCountySchools/', 'KY', 'Caldwell', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-calloway', 'Calloway County Schools', 'Kentucky - Schools', 'https://www.facebook.com/callowaycoschools/', 'KY', 'Calloway', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-campbell', 'Campbell County Schools', 'Kentucky - Schools', 'https://www.facebook.com/ccschoo1s/', 'KY', 'Campbell', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-carlisle', 'Carlisle County Public Schools', 'Kentucky - Schools', 'https://www.facebook.com/carlislecountypublicschools/', 'KY', 'Carlisle', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-carroll', 'Carroll County Schools', 'Kentucky - Schools', 'https://www.facebook.com/CarrollCountySchoolsKY/', 'KY', 'Carroll', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-carter', 'Carter County Schools', 'Kentucky - Schools', 'https://www.facebook.com/CarterCountySchoolsKY/', 'KY', 'Carter', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-casey', 'Casey County Schools', 'Kentucky - Schools', 'https://www.facebook.com/CaseyCountySchools/', 'KY', 'Casey', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-christian', 'Christian County Public Schools', 'Kentucky - Schools', 'https://www.facebook.com/ChristianCountyPublicSchools/', 'KY', 'Christian', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-clark', 'Clark County Public Schools', 'Kentucky - Schools', 'https://www.facebook.com/ClarkCountyPublicSchoolsKY/', 'KY', 'Clark', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-clay', 'Clay County Public Schools', 'Kentucky - Schools', 'https://www.facebook.com/ClayCountyPublicSchools/', 'KY', 'Clay', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-clinton', 'Clinton County Schools', 'Kentucky - Schools', 'https://www.facebook.com/ClintonCountySchoolsKY/', 'KY', 'Clinton', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-crittenden', 'Crittenden County Schools', 'Kentucky - Schools', 'https://www.facebook.com/CrittendenCountySchools/', 'KY', 'Crittenden', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-cumberland', 'Cumberland County Schools', 'Kentucky - Schools', 'https://www.facebook.com/CumberlandCountySchoolsKY/', 'KY', 'Cumberland', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-daviess', 'Daviess County Public Schools', 'Kentucky - Schools', 'https://www.facebook.com/DCPSchools/', 'KY', 'Daviess', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-edmonson', 'Edmonson County Schools', 'Kentucky - Schools', 'https://www.facebook.com/EdmonsonCoSchools/', 'KY', 'Edmonson', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-elliott', 'Elliott County Schools', 'Kentucky - Schools', 'https://www.facebook.com/ElliottCoSchools/', 'KY', 'Elliott', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-estill', 'Estill County Schools', 'Kentucky - Schools', 'https://www.facebook.com/EstillCountySchools/', 'KY', 'Estill', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-fayette', 'Fayette County Public Schools', 'Kentucky - Schools', 'https://www.facebook.com/fayettecountyschools/', 'KY', 'Fayette', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-fleming', 'Fleming County Schools', 'Kentucky - Schools', 'https://www.facebook.com/FlemingCountySchools/', 'KY', 'Fleming', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-floyd', 'Floyd County Schools', 'Kentucky - Schools', 'https://www.facebook.com/floydcountyschools/', 'KY', 'Floyd', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-franklin', 'Franklin County Public Schools', 'Kentucky - Schools', 'https://www.facebook.com/FranklinCountySchoolsKY/', 'KY', 'Franklin', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-fulton', 'Fulton County Public Schools', 'Kentucky - Schools', 'https://www.facebook.com/FultonCountySchoolDistrict/', 'KY', 'Fulton', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-gallatin', 'Gallatin County Schools', 'Kentucky - Schools', 'https://www.facebook.com/GallatinCountySchoolsKY/', 'KY', 'Gallatin', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-garrard', 'Garrard County Schools', 'Kentucky - Schools', 'https://www.facebook.com/GarrardCountySchools/', 'KY', 'Garrard', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-grant', 'Grant County Schools', 'Kentucky - Schools', 'https://www.facebook.com/GrantCountySchoolsKY/', 'KY', 'Grant', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-graves', 'Graves County Schools', 'Kentucky - Schools', 'https://www.facebook.com/GravesCountySchoolsKY/', 'KY', 'Graves', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-grayson', 'Grayson County Schools', 'Kentucky - Schools', 'https://www.facebook.com/GraysonCountySchools/', 'KY', 'Grayson', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-green', 'Green County Schools', 'Kentucky - Schools', 'https://www.facebook.com/GreenCountySchoolsKY/', 'KY', 'Green', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-greenup', 'Greenup County Schools', 'Kentucky - Schools', 'https://www.facebook.com/GreenupCountySchoolsKY/', 'KY', 'Greenup', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-hancock', 'Hancock County Schools', 'Kentucky - Schools', 'https://www.facebook.com/HancockCoSchoolsKY/', 'KY', 'Hancock', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-hardin', 'Hardin County Schools', 'Kentucky - Schools', 'https://www.facebook.com/HardinCountySchoolsKY/', 'KY', 'Hardin', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-harlan', 'Harlan County Public Schools', 'Kentucky - Schools', 'https://www.facebook.com/HarlanCountyPublicSchools/', 'KY', 'Harlan', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-harrison', 'Harrison County Schools', 'Kentucky - Schools', 'https://www.facebook.com/HarrisonCountySchoolsKY/', 'KY', 'Harrison', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-hart', 'Hart County Schools', 'Kentucky - Schools', 'https://www.facebook.com/HartCountySchoolsKY/', 'KY', 'Hart', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-henderson', 'Henderson County Schools', 'Kentucky - Schools', 'https://www.facebook.com/HendersonCountySchoolsKY/', 'KY', 'Henderson', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-henry', 'Henry County Schools', 'Kentucky - Schools', 'https://www.facebook.com/HenryCountySchools/', 'KY', 'Henry', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-hickman', 'Hickman County Schools', 'Kentucky - Schools', 'https://www.facebook.com/HickmanCountySchoolsKY/', 'KY', 'Hickman', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-hopkins', 'Hopkins County Schools', 'Kentucky - Schools', 'https://www.facebook.com/hopkinscountyschools/', 'KY', 'Hopkins', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-jackson', 'Jackson County Public Schools', 'Kentucky - Schools', 'https://www.facebook.com/JacksonCountyPublicSchoolsKY/', 'KY', 'Jackson', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-jefferson', 'Jefferson County Public Schools', 'Kentucky - Schools', 'https://www.facebook.com/JCPSKY/', 'KY', 'Jefferson', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-jessamine', 'Jessamine County Schools', 'Kentucky - Schools', 'https://www.facebook.com/JessamineCountyKY/', 'KY', 'Jessamine', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-johnson', 'Johnson County Schools', 'Kentucky - Schools', 'https://www.facebook.com/JohnsonCountySchoolsKY/', 'KY', 'Johnson', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-kenton', 'Kenton County School District', 'Kentucky - Schools', 'https://www.facebook.com/KentonCountySchoolDistrict/', 'KY', 'Kenton', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-knott', 'Knott County Schools', 'Kentucky - Schools', 'https://www.facebook.com/KnottCountySchools/', 'KY', 'Knott', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-knox', 'Knox County Schools', 'Kentucky - Schools', 'https://www.facebook.com/KnoxCountySchoolDistrictKY/', 'KY', 'Knox', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-larue', 'LaRue County Schools', 'Kentucky - Schools', 'https://www.facebook.com/LaRueCountySchools/', 'KY', 'Larue', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-laurel', 'Laurel County Public Schools', 'Kentucky - Schools', 'https://www.facebook.com/LaurelCountyPublicSchoolsKY/', 'KY', 'Laurel', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-lawrence', 'Lawrence County Schools', 'Kentucky - Schools', 'https://www.facebook.com/LawrenceCountySchoolsKY/', 'KY', 'Lawrence', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-lee', 'Lee County Schools', 'Kentucky - Schools', 'https://www.facebook.com/LeeCountySchoolsKY/', 'KY', 'Lee', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-leslie', 'Leslie County Schools', 'Kentucky - Schools', 'https://www.facebook.com/LeslieCountySchools/', 'KY', 'Leslie', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-letcher', 'Letcher County Schools', 'Kentucky - Schools', 'https://www.facebook.com/LetcherCountySchools/', 'KY', 'Letcher', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-lewis', 'Lewis County Schools', 'Kentucky - Schools', 'https://www.facebook.com/LewisCoSchools/', 'KY', 'Lewis', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-lincoln', 'Lincoln County Schools', 'Kentucky - Schools', 'https://www.facebook.com/LincolnCountySchoolsKY/', 'KY', 'Lincoln', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-livingston', 'Livingston County Schools', 'Kentucky - Schools', 'https://www.facebook.com/LivingstonCountyKY/', 'KY', 'Livingston', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-logan', 'Logan County Schools', 'Kentucky - Schools', 'https://www.facebook.com/LoganCountySchoolsKY/', 'KY', 'Logan', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-lyon', 'Lyon County Schools', 'Kentucky - Schools', 'https://www.facebook.com/LyonCountySchoolsKY/', 'KY', 'Lyon', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-mccracken', 'McCracken County Public Schools', 'Kentucky - Schools', 'https://www.facebook.com/McCrackenCountyPublicSchools/', 'KY', 'McCracken', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-mccreary', 'McCreary County Schools', 'Kentucky - Schools', 'https://www.facebook.com/McCrearyCountySchools/', 'KY', 'McCreary', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-metcalfe', 'Metcalfe County Schools', 'Kentucky - Schools', 'https://www.facebook.com/MetcalfeCountySchoolsKY/', 'KY', 'Metcalfe', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-monroe', 'Monroe County Schools', 'Kentucky - Schools', 'https://www.facebook.com/MonroeCountySchoolsKY/', 'KY', 'Monroe', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-montgomery', 'Montgomery County Schools', 'Kentucky - Schools', 'https://www.facebook.com/MontgomeryCountyKYSchools/', 'KY', 'Montgomery', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-morgan', 'Morgan County Schools', 'Kentucky - Schools', 'https://www.facebook.com/MorganCountySchoolsKY/', 'KY', 'Morgan', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-muhlenberg', 'Muhlenberg County Schools', 'Kentucky - Schools', 'https://www.facebook.com/MuhlenbergCountySchools/', 'KY', 'Muhlenberg', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-nelson', 'Nelson County Schools', 'Kentucky - Schools', 'https://www.facebook.com/NelsonCountyKySchools/', 'KY', 'Nelson', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-nicholas', 'Nicholas County Schools', 'Kentucky - Schools', 'https://www.facebook.com/NicholasCountySchoolsKY/', 'KY', 'Nicholas', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-ohio', 'Ohio County Schools', 'Kentucky - Schools', 'https://www.facebook.com/OhioCountySchoolsKY/', 'KY', 'Ohio', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-oldham', 'Oldham County Schools', 'Kentucky - Schools', 'https://www.facebook.com/OldhamCountySchools/', 'KY', 'Oldham', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-owen', 'Owen County Schools', 'Kentucky - Schools', 'https://www.facebook.com/OwenCountySchoolsKY/', 'KY', 'Owen', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-owsley', 'Owsley County Schools', 'Kentucky - Schools', 'https://www.facebook.com/OwsleyCountySchoolsKY/', 'KY', 'Owsley', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-pendleton', 'Pendleton County Schools', 'Kentucky - Schools', 'https://www.facebook.com/PendletonCountySchoolsKY/', 'KY', 'Pendleton', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-perry', 'Perry County Schools', 'Kentucky - Schools', 'https://www.facebook.com/PerryCountySchoolsKY/', 'KY', 'Perry', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-pike', 'Pike County Schools', 'Kentucky - Schools', 'https://www.facebook.com/PikeCountySchoolsKY/', 'KY', 'Pike', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-powell', 'Powell County Schools', 'Kentucky - Schools', 'https://www.facebook.com/PowellCountySchoolsKY/', 'KY', 'Powell', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-pulaski', 'Pulaski County Schools', 'Kentucky - Schools', 'https://www.facebook.com/pulaskicountyschools/', 'KY', 'Pulaski', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-robertson', 'Robertson County Schools', 'Kentucky - Schools', 'https://www.facebook.com/RobertsonCountySchools/', 'KY', 'Robertson', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-rockcastle', 'Rockcastle County Schools', 'Kentucky - Schools', 'https://www.facebook.com/RockcastleCountySchoolsKY/', 'KY', 'Rockcastle', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-rowan', 'Rowan County Schools', 'Kentucky - Schools', 'https://www.facebook.com/RowanCountySchoolsKY/', 'KY', 'Rowan', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-russell', 'Russell County Schools', 'Kentucky - Schools', 'https://www.facebook.com/RussellCountySchoolsKY/', 'KY', 'Russell', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-scott', 'Scott County Schools', 'Kentucky - Schools', 'https://www.facebook.com/scottcountyschools/', 'KY', 'Scott', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-shelby', 'Shelby County Schools', 'Kentucky - Schools', 'https://www.facebook.com/ShelbyCountyPublicSchoolsKY/', 'KY', 'Shelby', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-simpson', 'Simpson County Schools', 'Kentucky - Schools', 'https://www.facebook.com/SimpsonCountySchoolsKY/', 'KY', 'Simpson', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-spencer', 'Spencer County Schools', 'Kentucky - Schools', 'https://www.facebook.com/SpencerCoKYSchools/', 'KY', 'Spencer', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-taylor', 'Taylor County Schools', 'Kentucky - Schools', 'https://www.facebook.com/TaylorCountySchoolsKY/', 'KY', 'Taylor', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-todd', 'Todd County Schools', 'Kentucky - Schools', 'https://www.facebook.com/toddcountyschools/', 'KY', 'Todd', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-trigg', 'Trigg County Schools', 'Kentucky - Schools', 'https://www.facebook.com/TriggCountySchools/', 'KY', 'Trigg', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-trimble', 'Trimble County Schools', 'Kentucky - Schools', 'https://www.facebook.com/TrimbleCountySchoolsKY/', 'KY', 'Trimble', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-union', 'Union County Schools', 'Kentucky - Schools', 'https://www.facebook.com/UnionCountySchoolDistrict/', 'KY', 'Union', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-warren', 'Warren County Public Schools', 'Kentucky - Schools', 'https://www.facebook.com/WarrenCountySchools/', 'KY', 'Warren', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-washington', 'Washington County Schools', 'Kentucky - Schools', 'https://www.facebook.com/WashingtonCountyKYSchools/', 'KY', 'Washington', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-wayne', 'Wayne County Schools', 'Kentucky - Schools', 'https://www.facebook.com/WayneCountySchoolDistrict/', 'KY', 'Wayne', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-webster', 'Webster County Schools', 'Kentucky - Schools', 'https://www.facebook.com/WebsterCountySchoolsKY/', 'KY', 'Webster', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-whitley', 'Whitley County School District', 'Kentucky - Schools', 'https://www.facebook.com/WhitleyCountySchoolDistrict/', 'KY', 'Whitley', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-wolfe', 'Wolfe County Schools', 'Kentucky - Schools', 'https://www.facebook.com/WolfeCountyKYSchools/', 'KY', 'Wolfe', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-woodford', 'Woodford County Schools', 'Kentucky - Schools', 'https://www.facebook.com/WoodfordCountySchools/', 'KY', 'Woodford', 'ky', 'facebook-page', NULL, 1);

-- Missing counties not in original MD file
INSERT OR IGNORE INTO feeds (id, name, category, url, state_code, default_county, region_scope, fetch_mode, scraper_id, enabled) VALUES
  ('ky-fb-school-bullitt', 'Bullitt County Schools', 'Kentucky - Schools', 'https://www.facebook.com/BullittCountySchools/', 'KY', 'Bullitt', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-madison', 'Madison County Schools', 'Kentucky - Schools', 'https://www.facebook.com/madisoncoschools/', 'KY', 'Madison', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-magoffin', 'Magoffin County Schools', 'Kentucky - Schools', 'https://www.facebook.com/MagoffinCountySchoolsKY/', 'KY', 'Magoffin', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-marion', 'Marion County Schools', 'Kentucky - Schools', 'https://www.facebook.com/MarionCountyKYSchools/', 'KY', 'Marion', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-marshall', 'Marshall County Schools', 'Kentucky - Schools', 'https://www.facebook.com/MarshallCountySchoolsKY/', 'KY', 'Marshall', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-martin', 'Martin County Schools', 'Kentucky - Schools', 'https://www.facebook.com/MartinCountySchoolsKY/', 'KY', 'Martin', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-mason', 'Mason County Schools', 'Kentucky - Schools', 'https://www.facebook.com/MasonCountySchoolsKY/', 'KY', 'Mason', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-mclean', 'McLean County Schools', 'Kentucky - Schools', 'https://www.facebook.com/McLeanCountySchoolsKY/', 'KY', 'McLean', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-meade', 'Meade County Schools', 'Kentucky - Schools', 'https://www.facebook.com/MeadeCountySchoolsKY/', 'KY', 'Meade', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-menifee', 'Menifee County Schools', 'Kentucky - Schools', 'https://www.facebook.com/MenifeeCountySchoolsKY/', 'KY', 'Menifee', 'ky', 'facebook-page', NULL, 1),
  ('ky-fb-school-mercer', 'Mercer County Schools', 'Kentucky - Schools', 'https://www.facebook.com/MercerCountySchoolsKY/', 'KY', 'Mercer', 'ky', 'facebook-page', NULL, 1);

-- Perry Advocate: local Perry County news via Facebook
INSERT OR IGNORE INTO feeds (id, name, category, url, state_code, default_county, region_scope, fetch_mode, scraper_id, enabled) VALUES
  ('ky-fb-perry-advocate', 'Perry Advocate', 'Kentucky - Local', 'https://www.facebook.com/perryadvocate', 'KY', 'Perry', 'ky', 'facebook-page', NULL, 1);

-- Additional Leslie County search feeds to improve EKY coverage.
-- WYMT ARC tag-based feed for leslie-county labeled stories.
INSERT OR IGNORE INTO feeds (id, name, category, url, state_code, default_county, region_scope, fetch_mode, scraper_id, enabled) VALUES
  ('ky-wymt-leslie', 'WYMT Leslie County News', 'Kentucky - Regional', 'https://www.wymt.com/arc/outboundfeeds/rss/tag/leslie-county/?outputType=xml', 'KY', 'Leslie', 'ky', 'rss', NULL, 1),
  ('ky-wymt-leslie-search', 'WYMT Leslie County Search', 'Kentucky - Regional', 'https://www.bing.com/news/search?q=site%3Awymt.com%20%22Leslie%20County%22&format=rss', 'KY', 'Leslie', 'ky', 'rss', NULL, 1),
  ('ky-leslie-county-news', 'Leslie County News (Hyden)', 'Kentucky - County Watch', 'https://www.bing.com/news/search?q=%22Hyden%22%20Kentucky%20news&format=rss', 'KY', 'Leslie', 'ky', 'rss', NULL, 1);
